import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await auth()) || null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-10 justify-end px-10 py-3">
          {session?.user ? (
            <a href="/dashboard">
              <img
                className="rounded-full h-12"
                src={session.user.image}
                alt="User Avatar"
              />
            </a>
          ) : (
            <a href="/login">
              <p className="text-white border-white border-2 px-6 py-2 rounded">
                Sign In
              </p>
            </a>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
