import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-10 justify-end px-10 py-3">
        <button className="text-white border-white border-2 px-6 py-2 rounded">Add Item</button>
        <button className="text-white border-white border-2 px-6 py-2 rounded">Done</button>
        </nav>
        {children}
        </body>
    </html>
  );
}
